# Generated by Django 6.0.4 on 2026-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
    ]
