# Generated by Django 6.0.4 on 2026-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Photolink'),
        ),
    ]
