# Generated by Django 6.0.4 on 2026-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_thing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='things/', verbose_name='Photolink'),
        ),
    ]
