# Generated by Django 6.0.4 on 2026-04-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_thing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False, verbose_name='Is HR Manager'),
        ),
    ]
