# Generated by Django 6.0.4 on 2026-04-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_is_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hr',
        ),
    ]
