# Generated by Django 6.0.4 on 2026-04-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='things',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.order')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.thing')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
