# Generated by Django 6.0.4 on 2026-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of birth'),
        ),
    ]
