# Generated by Django 6.0.4 on 2026-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_certificate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Photolink'),
        ),
    ]
