# Generated by Django 6.0.4 on 2026-04-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_certificate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='File'),
        ),
    ]
